### PR TITLE
Simplifying Induction to Recursion

### PR DESCRIPTION
**Pull request by babu-akhil**
Done for Products, Sums and Coproduct Types. Identity type is still to be done.

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Do not cast, i.e., use `.asInstanceOf[..]` to change the type to something it is not. I do use it, but only if I know that something has type `U` but cannot prove this to the compiler.

**Comment by babu-akhil** [comment]
I thought it was ok since Func should be a subtype of FuncLike, i.e.,all
pure functions can be seen as dependent functions.

**Comment by siddhartha-gadgil** [comment]
* But your casting says that all functions with _domain_ all pure functions are functions with _domain_ all (not necessarily pure) functions. This is false.
* You can get the same effect by widening the type of variables, e.g. `val x: FuncLike[u, v] = typ.Var` which involves no casting.
* However, I have realized (due to the bug you uncovered) that this also has a danger when we apply the lambda. So one should presumably also modify the `def variable` method for `PiDefn` in the case of a constant `value` to give `SymbolicFunc` not `PiSymbolicFunc`.
* In any case, tests need to be added to make sure stuff works.

**Comment by siddhartha-gadgil** [comment]
* I have refined the `variable` function for `PiDefn` in 1a2fa81ab33b2a3ee97e1b60, and the previous `indfn == recfn` issue has been fixed more robustly.
* Hence using the explicit widening of the type of the variable should be safe.
* Nevertheless, we need to have tests for all cases before merging.

**Comment by babu-akhil** [comment]
- I tried widening the type of the variable and it works in the Product case but I've had to change the type of input variable for the class `InducFn` and also the type of `defndata`. We will have to check if this breaks anything else.

**Pull request closed without merging**
