### PR TITLE
Handling raised MatchExceptions in the Determiner Object and adding more adjective and adverb support

### PR DESCRIPTION
**Pull request by sundararajan-s**
Handles the issue regarding of a `MatchException` being raised by the Determiner Object by adding new cases and a new subclass for the handling 'both' #289.

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
The diffs are too large so it is hard to tell what actually changed. For example, why should `index.html` have changed. More seriously, it seems that stuff was reformatted so that when a few lines are added, existing code is reformatted so not matched with the old one.

**Comment by siddhartha-gadgil** [comment]
A couple of points:

* There is a `.scalafmt.conf`, so please reformat using scalafmt only (which is the standard).
* Perhaps the problem was that earlier I had a different format. In that case it may be better to have separate commits with reformatting only.
* It may not have been clear, but `index.html` is system generated. It should not be manually edited, but instead generated with `Site.mkSite()`. Please revert manual changes.

**Comment by sundararajan-s** [comment]
> The diffs are too large so it is hard to tell what actually changed. For example, why should `index.html` have changed. More seriously, it seems that stuff was reformatted so that when a few lines are added, existing code is reformatted so not matched with the old one.

I think this was due to reformatting. I shall fix that.



> A couple of points:
> 
> * There is a `.scalafmt.conf`, so please reformat using scalafmt only (which is the standard).
> * Perhaps the problem was that earlier I had a different format. In that case it may be better to have separate commits with reformatting only.
> * It may not have been clear, but `index.html` is system generated. It should not be manually edited, but instead generated with `Site.mkSite()`. Please revert manual changes.

I shall do that.

**Comment by sundararajan-s** [comment]
I shall redo this and create a different pull request.

**Pull request closed without merging**
